# Generated by Django 3.2.7 on 2021-10-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Enter your name')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter your email')),
                ('phone', models.IntegerField(max_length=100, verbose_name='Enter your phone number')),
                ('message', models.TextField(verbose_name='Enter your message')),
            ],
        ),
        migrations.CreateModel(
            name='Userfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Enter your names')),
                ('email', models.EmailField(max_length=100, verbose_name='Enter your email')),
                ('phone', models.IntegerField(max_length=100, verbose_name='Enter your phone number')),
                ('message', models.TextField(verbose_name='Enter your feedback message')),
            ],
        ),
    ]
