# Generated by Django 3.2.7 on 2021-10-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(choices=[('Airpeace', 'Airpeace'), ('Arik Air', 'Arik Air'), ('Dana Air', 'Dana Air'), ('Ibom Air', 'Ibom Air'), ('Aero Contractor', 'Aero Contractor')], max_length=100, verbose_name='Select Airline')),
                ('travelroute', models.CharField(choices=[('Lagos to Abuja', 'Lagos to Abuja'), ('Abuja to Lagos', 'Abuja to Lagos'), ('Asaba to Benin', 'Asaba to Benin'), ('Benin to Asaba', 'Benin to Asaba'), ('Kaduna to Jos', 'Kaduna to Jos'), ('Jos to Kaduna', 'Jos to Kaduna'), ('Port harcourt to Enugu', 'Port harcourt to Enugu'), ('Enugu to Port harcourt', 'Enugu to Port harcourt'), ('Warri to Sokoto', 'Warri to Sokoto'), ('Sokoto to warri', 'Sokoto to warri')], max_length=100, verbose_name='Select Routes')),
                ('routefee', models.IntegerField(verbose_name='Route Fee ')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Enter your names')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter your email')),
                ('phone', models.IntegerField(verbose_name='Enter your phone number')),
                ('options', models.CharField(choices=[('return', 'RETURN'), ('OneWay', 'ONEWAY')], max_length=100, verbose_name='Select return or one way')),
                ('goingdate', models.DateTimeField()),
                ('returndate', models.DateTimeField()),
                ('Trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.travelroutes')),
            ],
        ),
    ]
