# Generated by Django 3.2.7 on 2021-10-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_reservation_travelroutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeReservation_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('return', 'RETURN'), ('OneWay', 'ONEWAY')], max_length=100, verbose_name='Select return or one way')),
            ],
        ),
        migrations.CreateModel(
            name='MakeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Asaba', 'Asaba'), ('Benin', 'Benin'), ('Kaduna', 'Kaduna'), ('Jos', 'Jos'), ('Port harcourt', 'Port harcourt'), ('Enugu', 'Enugu'), ('Warri', 'Warri'), ('Sokoto', 'Sokoto')], max_length=100, verbose_name='Select Route')),
                ('routeType', models.CharField(choices=[('LOCAL', 'Local'), ('INTERNATINONAL', 'International')], max_length=100, verbose_name='Select Route')),
            ],
        ),
    ]
