# Generated by Django 3.2.7 on 2021-10-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_makereservation_2_makeroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Enter your names')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter your email')),
                ('phone', models.IntegerField(verbose_name='Enter your phone number')),
                ('options', models.CharField(choices=[('return', 'RETURN'), ('OneWay', 'ONEWAY')], max_length=100, verbose_name='Select return or one way')),
                ('goingdate', models.DateTimeField()),
                ('returndate', models.DateTimeField()),
                ('Trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.travelroutes')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_oneway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Enter your names')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter your email')),
                ('phone', models.IntegerField(verbose_name='Enter your phone number')),
                ('options', models.CharField(choices=[('return', 'RETURN'), ('OneWay', 'ONEWAY')], max_length=100, verbose_name='Select return or one way')),
                ('goingdate', models.DateTimeField()),
                ('Trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.travelroutes')),
            ],
        ),
    ]
