# Generated by Django 3.2.7 on 2021-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_reservation_oneway_reservation_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_oneway',
            name='Trip',
            field=models.CharField(max_length=100, verbose_name='You trip'),
        ),
        migrations.AlterField(
            model_name='reservation_oneway',
            name='options',
            field=models.CharField(max_length=100, verbose_name='You trip type'),
        ),
        migrations.AlterField(
            model_name='reservation_return',
            name='Trip',
            field=models.CharField(max_length=100, verbose_name='You trip'),
        ),
        migrations.AlterField(
            model_name='reservation_return',
            name='options',
            field=models.CharField(max_length=100, verbose_name='You trip type'),
        ),
    ]
