# Generated by Django 3.2.7 on 2021-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20211030_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_oneway',
            name='reserveId',
            field=models.CharField(default='12345', max_length=100, verbose_name=''),
        ),
        migrations.AddField(
            model_name='reservation_return',
            name='reserveId',
            field=models.CharField(default='12345', max_length=100, verbose_name=''),
        ),
    ]
