# Generated by Django 3.2.7 on 2021-11-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20211030_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeroute',
            name='routeName',
            field=models.CharField(choices=[('Lagos', 'Lagos'), ('Abuja', 'Abuja'), ('Asaba', 'Asaba'), ('Benin', 'Benin'), ('Kaduna', 'Kaduna'), ('Jos', 'Jos'), ('Portharcourt', 'Portharcourt'), ('Enugu', 'Enugu'), ('Warri', 'Warri'), ('Sokoto', 'Sokoto')], max_length=100, verbose_name='Select Route'),
        ),
    ]
