# Generated by Django 3.2.7 on 2021-11-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_makeroute_routename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveForm_oneway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(max_length=100, verbose_name='Your Route')),
                ('goingDate', models.DateField()),
                ('routeAirlineandFee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.travelroutes')),
            ],
        ),
    ]
