# Generated by Django 3.2.7 on 2021-11-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_reserveform_oneway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveform_oneway',
            name='routeName',
        ),
    ]
