# Generated by Django 3.2.7 on 2021-11-02 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_remove_reserveform_oneway_routename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveForm_return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goingDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('routeAirlineandFee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.travelroutes')),
            ],
        ),
    ]
